# interview
Explain your project(Flow)
1. Problem statements

In [28]:
# https://justpaste.it/b1jv9   h/w

In [29]:
            # CMD basics  
# to create a new folder using "cmd"
# 1. locate to your desired folder using "cd folder name"
# 2. "mkdir foldername" give name to your new folder
# 3. "code ." to enter in  vs code
# 4. and to go 1 step back in folder write "cd .." 

a = print("hello")
a

hello


In [30]:
import pandas as pd

In [31]:
data = pd.read_csv("Advertising (1).csv", index_col=0)
data.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [32]:
data.shape

(200, 4)

In [33]:
data.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [34]:
data.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB


In [36]:
data.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [37]:
print("in ml algorithm we can always predict only one column based on multiple columns")
x = data[['TV', 'Radio', 'Newspaper']]
y = data[['Sales']]

in ml algorithm we can always predict only one column based on multiple columns


In [38]:
print(x)

        TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]


In [39]:
                        # flow very important
#supervised or unsupervised
# we have both x and y(value to predict) then supervide
# if we dont have y, use unspuervised

# in supervised (how to choose classification and regression)
# choose regression if we want to predict something and the predicting column is cuntinuous(numerical) not categorical

In [40]:
            # Training
# Train and Test split
# 70% to 80% Training
# 20% to 30% testing

In [41]:
# linear regression working
# y = b0 + b1x1 + b2x2 + b3x3  (here b means beta)
# why only x1,x1,x3 coz we have 3 columns apart from the column(y) we have to predict

# note x = independent variable
#      y = dependent variable

# so first we have values of y and x in training data then we find b0, b1, b2, b3.
# now we have x and b on test data (well we also have y but we will use it to check) then using x and b we will find y and cross check this y with original test data

# on best fit line the b0 is the starting point on y-axis
# NOte the mean of a column is staright line parallel to x-axis

In [42]:
# best fit line
# it needs to be close to all datapoints 
# and when there is an Outlier then the bestfit line will also be close to that outliers which will shift our best fit line and prediction will be wrong

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)# chooses randomly 0.2 means 20% for testing

In [44]:
print(x_train.shape, "training data size for x")
print(x_test.shape,  "testing data size for x")
print(y_train.shape, "training data size for y")
print(y_test.shape,  "testing data size for y")

(160, 3) training data size for x
(40, 3) testing data size for x
(160, 1) training data size for y
(40, 1) testing data size for y


In [45]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
model = lm.fit(x_train, y_train)

In [46]:
model.coef_  # this is (b1, b2, b3)

array([[ 0.04523253,  0.19690197, -0.00411705]])

In [47]:
model.intercept_  # this is (b0)

array([2.95516756])

In [48]:
# y = b0 + b1x1 + b2x2 + b3x3

b0 = 3.03313258
b1 = 0.04626426
b2 = 0.18655545
b3 = -0.00037959

y = b0 + b1*230.1 + b2*37.8 + b3*69.2
print("this is pretty close to 22.1 and (predicted)y =", y)

this is pretty close to 22.1 and (predicted)y = 20.704067188000003


In [49]:
b0 = 3.03313258
b1 = 0.04626426
b2 = 0.18655545
b3 = -0.00037959

y = b0 + b1*44.5 + b2*39.3 + b3*45.1
print("this is pretty close to 10.4 and (predicted)y =", y)

this is pretty close to 10.4 and (predicted)y = 12.406401826


In [50]:
# so above we did manually

# we dont do that here, we use function
y_pred = model.predict(x_test) # it basically performs --> y = b0 + b1x1 + b2x2 + b3x3 on all rows
y_pred

array([[21.68221174],
       [15.5598265 ],
       [ 7.5291171 ],
       [13.25327386],
       [ 3.52107794],
       [23.25118752],
       [10.04640684],
       [ 7.52361071],
       [16.34594962],
       [13.01931412],
       [ 5.35477211],
       [14.76737828],
       [18.90573136],
       [10.74832995],
       [17.12199683],
       [17.8268343 ],
       [ 7.83640494],
       [21.5982442 ],
       [18.23654472],
       [13.85906405],
       [ 8.47206241],
       [10.52489281],
       [11.96183714],
       [19.15559888],
       [10.51635509],
       [ 7.8708124 ],
       [17.87558711],
       [21.02742046],
       [10.56398005],
       [11.95458525],
       [17.10799845],
       [16.71148484],
       [24.13522306],
       [15.69643071],
       [14.24524036],
       [13.63041518],
       [19.95565951],
       [19.78157449],
       [ 7.00774311],
       [10.75914505]])

In [51]:
# now to make it look good and readable
new_df = pd.DataFrame()
new_df = x_test 
new_df['actual sales']    = y_test
new_df['predicted sales'] = y_pred
new_df

TV  Radio  Newspaper  actual sales  predicted sales
43   293.6   27.7        1.8          20.7        21.682212
157   93.9   43.5       50.5          15.3        15.559827
35    95.7    1.4        7.4           9.5         7.529117
168  206.8    5.2       19.4          12.2        13.253274
109   13.1    0.4       25.6           5.3         3.521078
18   281.4   39.6       55.8          24.4        23.251188
19    69.2   20.5       18.3          11.3        10.046407
33    97.2    1.5       30.0           9.6         7.523611
96   163.3   31.6       52.9          16.9        16.345950
5    180.8   10.8       58.4          12.9        13.019314
196   38.2    3.7       13.8           7.6         5.354772
104  187.9   17.2       17.9          14.7        14.767378
34   265.6   20.0        0.3          17.4        18.905731
131    0.7   39.6        8.7           1.6        10.748330
90   109.8   47.8       51.4          16.7        17.121997
71   199.1   30.6       38.7          18.3        17.826834
130   59.6   12.0       43.1           9.7         7.836405
31   292.9   28.3       43.2          21.4        21.598244
151  280.7   13.9       37.0          16.1        18.236545
44   206.9    8.4       26.4          12.9        13.859064
192   75.5   10.8        6.0           9.9         8.472062
95   107.4   14.0       10.9          11.5        10.524893
117  139.2   14.3       25.6          12.2        11.961837
93   217.7   33.5       59.0          19.4        19.155599
181  156.6    2.6        8.3          10.5        10.516355
122   18.8   21.7       50.4           7.0         7.870812
170  284.3   10.6        6.4          15.0        17.875587
186  205.0   45.1       19.6          22.6        21.027420
159   11.7   36.9       45.2           7.3        10.563980
135   36.9   38.6       65.6          10.8        11.954585
169  215.4   23.6       57.6          17.1        17.107998
195  149.7   35.6        6.0          17.3        16.711485
184  287.6   43.0       71.8          26.2        24.135223
88   110.7   40.6       63.2          16.0        15.696431
20   147.3   23.9       19.1          14.6        14.245240
175  222.4    3.4       13.1          11.5        13.630415
140  184.9   43.9        1.7          20.7        19.955660
110  255.4   26.9        5.5          19.8        19.781574
108   90.4    0.3       23.2           8.7         7.007743
127    7.8   38.9       50.6           6.6        10.759145

In [52]:
# step 1= gathering data
# step 2 = preprocessing
# step 3 = training and testing
# step 4 = evaluation
# step 5 = tuning(enhance performance)



                # this is step 3 = EVALUATION

# NOTE supervised algos k liye r2_score and mean_squared_error hai)

import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
r2 = r2_score(y_test, y_pred)
print("R-square jitna 1 ke pass utna achha(iska range hota hai 0 to 1)")
print("R-square:",r2)
# The R-squared (R²) value of 0.8539 indicates that approximately 85.39% of the variance in the Sales is explained by your model. 
# This is generally considered a good value, suggesting that your model has a strong explanatory power. 



print()

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE jitna kam utna achha")
print("RMSE:",rmse)

# on average predictions deviate from the actual car prices by about 2.0844 dollars.

R-score jitna 1 ke pass utna achha(iska range hota hai 0 to 1)
R-score: 0.8539202398990502

RMSE jitna zyada utna achha
RMSE: 2.0844339549764004


# TASK

In [53]:
# kaggle.com/datasets/sharanmedamoni/toyoto


import pandas as pd

In [54]:
data2 = pd.read_csv("Toyota.csv", index_col= 0)

github 
0. interface
1. new(green color)
2. guve name to repo
3. make pubic
4. add readme file
5. create


go to readme-> go to pencilsign/(interview m bhi yehi explain karna hai)
1. problem statemnet
2. define dataset
3. mention all the null/incorrect symbol handling(if any)
4. whih algo used
5. mention = coefficient and intercept values
6. mention = RRMSE and R2_score values

how to add project in github
1. go on your repo 
2. click on code
3. copy the url
4. go in cmd (normal) 
5. write git
6. write git clone (paste the url) sample = git clone https://github.com/Ashking21101/Linear-Regression.git
7. cd Linear-Regression
8. now copy the code file and dataset file
9. and paste them in the above folder